### ISSUE TITLE
about custom font imports

### ISSUE THREAD

**Issue by xlyylk** [ginsudev/WDBFontOverwrite#10]
I installed v1.3 with a certificate on ios15.6rc, iPhone xr, but it didn't respond when importing .ttf and .ttc.  But I saw in other forums that it can be used with altstore or Bullforg Assistant. Is this a bug or only me or some devices have bugs?

**Comment by weishashadoudabuliao** [comment]
I have this issue too, I'm using an iPad8 Ios15.2. Installed by troll store.

**Comment by PeakGymnast** [comment]
Same here, individual certification does not take the effect and respond when importing ttf file. But when using Bullforg to install the app, it worked

**Comment by xlyylk** [comment]
> Same here, individual certification does not take the effect and respond when importing ttf file. But when using Bullforg to install the app, it worked

Yes, indeed.

So I was wondering if this problem could be solved

**Comment by IntelCorei5-8350u** [comment]
I couldn't install custom emojis on my 6splus running on 15.7.1 but I could install it on my mini6 running on 15.4.1. This bug is weird since it seems to be device specific

**Comment by xlyylk** [comment]
> I couldn't install custom emojis on my 6splus running on 15.7.1 but I could install it on my mini6 running on 15.4.1. This bug is weird since it seems to be device specific

emm，thats so weird

**Comment by xlyylk** [comment]
> I couldn't install custom emojis on my 6splus running on 15.7.1 but I could install it on my mini6 running on 15.4.1. This bug is weird since it seems to be device specific

emm，thats so weird

**Comment by zhuowei** [comment]
Could you try https://github.com/zhuowei/WDBFontOverwrite/releases/tag/v1.4 and see if this fixes it?

**Comment by xlyylk** [comment]
> Could you try https://github.com/zhuowei/WDBFontOverwrite/releases/tag/v1.4 and see if this fixes it?

It's strange, I tried v1.4 but I still can't import custom files using certificate installation.

**Comment by zhuowei** [comment]
ok, I'll try again. How are you installing this? I'm testing by installing through Xcode, so I don't know how to reproduce your setup

**Comment by xlyylk** [comment]
> ok, I'll try again. How are you installing this? I'm testing by installing through Xcode, so I don't know how to reproduce your setup

I installed it using an application called "Esign". I use a personal certificate. By the way, thanks for your efforts

**Comment by IntelCorei5-8350u** [comment]
> Could you try https://github.com/zhuowei/WDBFontOverwrite/releases/tag/v1.4 and see if this fixes it?

I can successfully import custom emojis but failed when installing it by clicking "Custom Emoji". The app is also installed using a third party app with a personal certificate like the guy above called "Sideloadly"

**Comment by zhuowei** [comment]
Can you try this? https://github.com/zhuowei/WDBFontOverwrite/releases/download/v1.4/WDBFontOverwrite-1.5b1.ipa

**Comment by xlyylk** [comment]
> Can you try this? https://github.com/zhuowei/WDBFontOverwrite/releases/download/v1.4/WDBFontOverwrite-1.5b1.ipa

Ok, I just installed v1.5 using the certificate and he solved perfectly the problem that the certificate installation could not be imported

**Comment by zhuowei** [comment]
Thanks for testing! I guess UIDocumentPickerViewController only works with .asCopy when sideloaded? That's really weird.

**Comment by IntelCorei5-8350u** [comment]
> > Could you try https://github.com/zhuowei/WDBFontOverwrite/releases/tag/v1.4 and see if this fixes it?
> 
> I can successfully import custom emojis but failed when installing it by clicking "Custom Emoji". The app is also installed using a third party app with a personal certificate like the guy above called "Sideloadly"

Regarding this comment the problem is still there even on v1.5. I wanted to import google noto emojis so badly
