### ISSUE TITLE
Fonts not changing iOS 16.1.2

### ISSUE THREAD

**Issue by binnichtaktiv** [ginsudev/WDBFontOverwrite#15]
The fonts are not changing. It only changed to one font no matter what font I select. 
iPhone 11 iOS 16.1.2

https://user-images.githubusercontent.com/96953964/209857107-adcb18c6-0c6a-42fb-9b0d-1e6e71d9d16e.MOV

**Comment by sachinfuria** [comment]
Plz help same problem

**Comment by binnichtaktiv** [comment]
> Plz help same problem

What iOS version are you on?

**Comment by binnichtaktiv** [comment]
Ohh shit I didn’t notice that I had bold text on my bad not everything is working
