### ISSUE TITLE
Memory usage issues

### ISSUE THREAD

**Issue by Xarth-Mai** [ginsudev/WDBFontOverwrite#26]
正如标题所示，替换较大的中文字体将导致严重的内存使用，导致小部件无法加载，第三方键盘无法运行，运行缓慢并反复注销。
更改字体后通过修改系统首选语言注销基板可以使替换的字体覆盖更多界面，但这会导致更多的内存问题。

As the title shows, replacing larger Chinese fonts will lead to severe memory usage, causing widgets to not to load, third-party keyboards cannot run, slow to run and repeatedly log out.
After changing the font, the replacement font can overwrite more interfaces by modifying the system's preferred language logout substrate, but this will lead to more memory problems.

**Comment by Vanyoo** [comment]
+1. Hope someone can resolve it…

**Comment by Xarth-Mai** [comment]
> 正如标题所示，替换较大的中文字体将导致严重的内存使用，导致小部件无法加载，第三方键盘无法运行，运行缓慢并反复注销。 更改字体后通过修改系统首选语言注销基板可以使替换的字体覆盖更多界面，但这会导致更多的内存问题。
> 
> 如标题所示，替换较大的中文字体将导致严重的内存使用，导致小部件无法加载，第三方键盘无法运行，运行缓慢并反复注销。更改字体后，替换字体可以通过修改系统的首选语言注销基板来覆盖更多接口，但这会导致更多的内存问题。

**Comment by Xarth-Mai** [comment]
done

**Comment by Xarth-Mai** [comment]
iPhoneXr在iOS16.1.2上使用1.10.5版本测试,问题已经解决(3G RAM)

iPhone Xr tested with version 1.10.2 on iOS 16.1.2, the issue has been resolved
