### ISSUE TITLE
Can't reset to stock font

### ISSUE THREAD

**Issue by CySxL** [ginsudev/WDBFontOverwrite#3]
So yes I tried reboot multiple times and the custom fonts still remain on my whole UI. Installed by TrollStore.

Device: iPhone 11 Pro Max
iOS: 14.8
Jailbreak: unc0ver 8.0.2
TrollStore: 1.4.5
WDBFontOverwrite: 1.2

**Comment by CySxL** [comment]
Solved by replacing the stock font file in `/System/Library/Fonts/CoreUI/SFUI.ttf`

Hope we get a revert stock font button for TrollStore + jailbroken users as it's permanently signed and somehow still persists after reboots.

**Comment by hoemotion** [comment]
> Solved by replacing the stock font file in `/System/Library/Fonts/CoreUI/SFUI.ttf`
> 
> Hope we get a revert stock font button for TrollStore + jailbroken users as it's permanently signed and somehow still persists after reboots.

Sorry, I am also facing this issue right know and couldn‘t understand what exactly you replaced the file with, would appreciate any help

**Comment by CySxL** [comment]
> > Solved by replacing the stock font file in `/System/Library/Fonts/CoreUI/SFUI.ttf`
> 
> > 
> 
> > Hope we get a revert stock font button for TrollStore + jailbroken users as it's permanently signed and somehow still persists after reboots.
> 
> 
> 
> Sorry, I am also facing this issue right know and couldn‘t understand what exactly you replaced the file with, would appreciate any help



https://www.reddit.com/r/jailbreak/comments/zxm9i7/tip_do_not_install_wdbfontoverwrite_via/

**Comment by hoemotion** [comment]
> > > Solved by replacing the stock font file in `/System/Library/Fonts/CoreUI/SFUI.ttf`
> > 
> > 
> > > 
> > 
> > 
> > > Hope we get a revert stock font button for TrollStore + jailbroken users as it's permanently signed and somehow still persists after reboots.
> > 
> > 
> > Sorry, I am also facing this issue right know and couldn‘t understand what exactly you replaced the file with, would appreciate any help
> 
> https://www.reddit.com/r/jailbreak/comments/zxm9i7/tip_do_not_install_wdbfontoverwrite_via/

Thanks mate 🙏
